export const FETCH_ATTRIBUTES_SUCCESS = "FETCH_ATTRIBUTES_SUCCESS";
export const FETCH_ATTRIBUTES_FAILURE = "FETCH_ATTRIBUTES_FAILURE";
export const FETCH_ATTRIBUTES_REQUEST = "FETCH_ATTRIBUTES_REQUEST";
