export const UPDATE_CUSTOMER_ADDRESS_SUCCESS = "UPDATE_CUSTOMER_ADDRESS_SUCCESS";
export const UPDATE_CUSTOMER_ADDRESS_FAILURE = "UPDATE_CUSTOMER_ADDRESS_FAILURE";
export const UPDATE_CUSTOMER_ADDRESS_REQUEST = "UPDATE_CUSTOMER_ADDRESS_REQUEST";
