export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";
export const FETCH_DEPARTMENT_REQUEST = "FETCH_DEPARTMENT_REQUEST";
