export const FETCH_PRODUCTS_BY_CATEGORY_SUCCESS = "FETCH_PRODUCTS_BY_CATEGORY_SUCCESS";
export const FETCH_PRODUCTS_BY_CATEGORY_FAILURE = "FETCH_PRODUCTS_BY_CATEGORY_FAILURE";
export const FETCH_PRODUCTS_BY_CATEGORY_REQUEST = "FETCH_PRODUCTS_BY_CATEGORY_REQUEST";
