export const FETCH_SHOPPING_CART_SUCCESS = "FETCH_SHOPPING_CART_SUCCESS";
export const FETCH_SHOPPING_CART_FAILURE = "FETCH_SHOPPING_CART_FAILURE";
export const FETCH_SHOPPING_CART_REQUEST = "FETCH_SHOPPING_CART_REQUEST";
