export const FETCH_TOTAL_AMOUNT_CART_SUCCESS = "FETCH_TOTAL_AMOUNT_CART_SUCCESS";
export const FETCH_TOTAL_AMOUNT_CART_FAILURE = "FETCH_TOTAL_AMOUNT_CART_FAILURE";
export const FETCH_TOTAL_AMOUNT_CART_REQUEST = "FETCH_TOTAL_AMOUNT_CART_REQUEST";
